# 配置项目名和session的过期时间
server:
  servlet:
    context-path: /wangpan
    session:
      timeout: 60m
  tomcat:
    uri-encoding: UTF-8
spring:
  #静态资源
  mvc:
    static-path-pattern: /** #配置静态访问资源
    #配置数据源
  datasource:
    username: 
    password: 
    url: jdbc:mysql://127.0.0.1:3306/moti-cloud?serverTimezone=Hongkong&useAffectedRows=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  # 配置邮件任务
  mail:
    username: 
    password: 
    host: smtp.qq.com
    port: 465
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          socketFactory:
            port: 465
            class: javax.net.ssl.SSLSocketFactory
            fallback: false
  thymeleaf:
    prefix: classpath:/templates/  #prefix：指定模板所在的目录
    check-template-location: true  #check-tempate-location: 检查模板路径是否存在
    cache: false  #cache: 是否缓存，开发模式下设置为false，避免改了模板还要重启服务器，线上设置为true，可以提高性能。
    suffix:  .html
    #encoding: UTF-8
    #content-type: text/html
    mode: HTML5
logging:
  #日志配置,存放位置以及级别
  file:
    name: log/wangpan.log
  level:
    root: info
